### ISSUE TITLE
Glitchy scrollbar

### ISSUE THREAD

**Issue by lcdsantos** [nfour/Sublime-Theme-Cola#1]
When I scroll, the code-view scrollbar gets weird:

![glitchy](https://cloud.githubusercontent.com/assets/910974/7038358/fad63392-dd86-11e4-816a-ed151b6b641e.png)

In Soda this doesn't happen. Any idea why?

I'm on Windows 7 x64
Sublime Text 3 Build 3083

**Comment by nfour** [comment]
Ah, I'm using sublime's `"overlay_scroll_bars": "enabled"` (User preference) which makes the scrollbar work like Mac OSX scrollbars, thus I missed that.

I'll fix this issue though, it seems like it is just some leftover opacity debugging I made to the scrollbars (for which I didn't see).

**Comment by lcdsantos** [comment]
It's perfect now, thanks! :smiley:
