### ISSUE TITLE
fix ST3 3090+ Sidebar php icon support

### ISSUE THREAD

**Issue by momoca** [nfour/Sublime-Theme-Cola#2]
open:
Theme - Cola.sublime-package\icons\icon_php.tmPreferences
[code Line 6](https://github.com/nfour/Sublime-Theme-Cola/blob/master/icons/icon_php.tmPreferences#L6):
`source`.php
replace
`embedding`.php

**Comment by nfour** [comment]
Thanks, fixed.

**Comment by momoca** [comment]
...

**Comment by nfour** [comment]
What?
