### ISSUE TITLE
soda classic tabs

### ISSUE THREAD

**Issue by victorwpbastos** [nfour/Sublime-Theme-Cola#3]
When soda classic tabs is set, the tabs can't be clicked.

![image](https://cloud.githubusercontent.com/assets/1017515/10806945/9bd3ab1e-7dc1-11e5-8976-7e399aa2d326.png)

**Comment by nfour** [comment]
I can confirm this. I'm not sure what it is at a glance though that is causing it. 

I wonder if it's a bug in the base soda theme on Sublime 8083+ or if it's some kind of layer depth issue or padding issue.

You can mousewheel through them, but that's about it. Will investigate.

**Comment by nfour** [comment]
Turns out it was an easy fix, changing `hit_test_level`.
